withfoodmate/frontend

- package.json
- src/main.tsx
- yarn.lock
- Recoil 상태관리 라이브러리 추가
- Recoil 라이브러리 추가
- 루트컴포넌트에 `RecoilRoot` 추가
- 
-
> FOOMATE #4 Recoil 상태관리 기본셋팅

- package.json
- src/components/common/BasicButton.tsx
- src/styles/GlobalStyle.ts
- yarn.lock
- BasicButton 컴포넌트 생성
- 동적 버튼 컴포넌트 생성
- 폰트 크기, 폰트 색상, 배경색, 테두리색, 마우스 오버 시 폰트 색상, 마우스 오버 시 배경색
- 로컬 폰트 생성 및 적용
> FOODMATE #23 BasicButton 컴포넌트 추가 및 로컬 폰트 적용

- src/components/common/Nav.tsx
- src/components/main-page/Ranking.tsx
- src/components/main-page/TodayMeeting.tsx
- src/constants/ranking.ts
- src/mocks/rankingData.ts
- src/styles/GlobalStyle.ts
- yarn.lock
- 랭킹 컴포넌트 개발
- 랭킹 컴포넌트 퍼블리싱
- 랭킹 테스트 데이터 생성
- nav 컴포넌트 수정
- ISSUE #39
> FOODMATE #39 랭킹 컴포넌트 개발

- src/App.tsx
- src/components/common/SideMenu.tsx
- src/components/meetingInfo/MeetingInfoCard.tsx
- src/components/meetingInfo/MeetingInfoCardList.tsx
- src/constants/menu.ts
- src/constants/nav-menus.ts
- src/pages/History.tsx
- src/pages/Inquiry.tsx
- src/styles/DefaultTheme.ts
- 신청 내역 라우트 및 페이지 생성
- 퍼블리싱
- 사이드 메뉴 구현
- 카테고리 분기 처리
- dropdown 컴포넌트 사용
- 타이틀 및 신청 상태 등 세부적인 디자인 수정 필요
- 데이터 연동 시 무한스크롤 구현 필요
#54
> FOODMATE #54 모임 정보 - 신청 내역 페이지 생성

- index.html
- src/App.tsx
- src/components/common/AlertModal.tsx
- src/components/common/SideMenu.tsx
- src/components/meetingInfo/MeetingInfoCard.tsx
- src/components/meetingInfo/MeetingInfoCardList.tsx
- src/components/meetingInfo/MeetingInfoRequestCard.tsx
- src/components/meetingInfo/MeetingInfoRequestCardList.tsx
- src/constants/menu.ts
- src/constants/nav-menus.ts
- src/pages/History.tsx
- src/pages/Inquiry.tsx
- src/styles/DefaultTheme.ts
- 모임 정보 - 요청 조회 페이지 생성
- 페이지 라우트
- 요청 수락/거절 클릭 시 AlertModal 컴포넌트 동작
- 받은 요청/처리된 요청 카테고리 나누기
- #55
> FOODMATE #55 모임 정보 - 요청 조회 페이지

- package.json
- src/vite-env.d.ts
- tsconfig.json
- tsconfig.node.json
- vite.config.ts
- yarn.lock
- 프록시 설정
- 프록시 설정 후 data fetch 확인
- CORS error 처리 백엔드에 요청
- #70
> [feat] 프록시 설정

- package.json
- src/main.tsx
- yarn.lock
- react-query 세팅
- 라이브러리 설치 및 세팅
- 세팅 후 data fetch 확인
- #78
> FOODMATE #78 react-query 설치 및 세팅

- package-lock.json
- package.json
- src/api/groupApi.ts
- src/components/common/BasicInput.tsx
- src/components/common/PostCard.tsx
- src/components/common/PostCardsList.tsx
- src/components/findFoodmate/DatePickerInput.tsx
- src/components/findFoodmate/DatePickers.tsx
- src/components/findFoodmate/MenuLabels.tsx
- src/components/kakao/CurrentLocation.tsx
- src/hooks/useCurrentLocation.ts
- src/pages/FindFoodmate.tsx
- src/types/postCardType.ts
- src/utils/formatDate.ts
- yarn.lock
- 페이지 기능 추가 및 리팩토링
- 데이터 연동
- 필터링 기능
- 검색 기능
- 무한스크롤
- #69
> FOODMATE #69 밥 친구 구해요 데이터 연동

- package-lock.json
- package.json
- src/api/groupApi.ts
- src/components/common/BasicInput.tsx
- src/components/common/PostCard.tsx
- src/components/common/PostCardsList.tsx
- src/components/findFoodmate/DatePickerInput.tsx
- src/components/findFoodmate/DatePickers.tsx
- src/components/findFoodmate/MenuLabels.tsx
- src/components/kakao/CurrentLocation.tsx
- src/components/meetingPostDetailView/Comments.tsx
- src/components/meetingPostDetailView/CommentsList.tsx
- src/hooks/useCurrentLocation.ts
- src/pages/FindFoodmate.tsx
- src/pages/MeetingPostDetailView.tsx
- src/types/postCardType.ts
- src/utils/formatDate.ts
- yarn.lock
- 모임글 상세페이지 데이터 연동
- groupId로 특정 모임 데이터 가져오기
- 모임 참여 alert
- 대화 참여 alert
- 댓글, 대댓글 가져오기
- 댓글, 대댓글 타입 리팩토링
- #89 
- #33
> FOODMATE #89 모임글 상세페이지 데이터 연동

- src/api/groupApi.ts
- src/components/common/PostCard.tsx
- src/components/findFoodmate/MenuLabels.tsx
- src/pages/CreateGroupPost.tsx
- src/types/postCardType.ts
- src/utils/removeDot.ts
- 모임 생성 구현
- 누락된 time 추가
- 모임 데이터 백단에 요청
- #83 
- #41
> FOODMATE #83 모임 생성 기능 추가

- src/api/fetchCall.ts
- src/api/groupApi.ts
- src/components/meetingPostDetailView/Comments.tsx
- src/components/meetingPostDetailView/CommentsList.tsx
- src/components/meetingPostDetailView/CreateComments.tsx
- src/pages/CreateGroupPost.tsx
- src/pages/MeetingPostDetailView.tsx
- src/pages/ModifyPost.tsx
- fetchCall 함수 공용
- 공통 fetchCall 함수 생성
- get 제외 api 호출 전체 함수 리팩토링
- 댓글 등록
#102
> Feature/jihye #102 공용 fetchCall 함수 생성 및 댓글 등록 기능

- src/api/fetchCall.ts
- src/api/memberApi.ts
- src/components/meetingPostDetailView/CommentsList.tsx
- src/components/meetingPostDetailView/CreateComments.tsx
- src/pages/Login.tsx
- src/pages/MeetingPostDetailView.tsx
- src/utils/getRefreshTokenCookie.ts
- 댓글 기능 추가
- 댓글 수정
- 댓글 삭제
- #106 
- 대댓글 CRUD 보류
> FOODMATE #106 댓글 수정/삭제

- src/App.tsx
- src/api/fetchCall.ts
- src/api/memberApi.ts
- src/components/common/AlertModal.tsx
- src/components/common/PrivateRoute.tsx
- src/components/meetingInfo/MeetingInfoRequestCard.tsx
- src/components/meetingInfo/MeetingInfoRequestCardList.tsx
- src/constants/nav-menus.ts
- src/pages/FindFoodmate.tsx
- src/pages/History.tsx
- src/pages/Inquiry.tsx
- src/pages/Neighborhood.tsx
- src/store/meetingInfo.ts
- src/types/postCardType.ts
- src/utils/getRefreshTokenCookie.ts
- 요청 조회 페이지 구현
- 받은 요청 데이터 fetch
- 수락한 요청 fetch
- 수락 처리
- 거절 처리
- #108
> FOODMATE #108 요청 조회 페이지 데이터 연동

- src/App.tsx
- src/api/fetchCall.ts
- src/api/memberApi.ts
- src/components/common/PostCard.tsx
- src/components/common/PrivateRoute.tsx
- src/components/common/ProfileModal.tsx
- src/components/meetingPostDetailView/Comments.tsx
- src/components/meetingPostDetailView/CommentsList.tsx
- src/pages/Login.tsx
- src/pages/MeetingPostDetailView.tsx
- src/store/login.ts
- src/store/userInfo.ts
- src/utils/getRefreshTokenCookie.ts
- 프로필 모달에 데이터 연동
- 프로필 데이터 연동
- 프로필 사진 클릭 시 해당 유저 정보 보여주기
- #111 
- #29
> FOODMATE #111 프로필 모달 기능 추가

- src/api/memberApi.ts
- src/components/common/PostCard.tsx
- src/components/common/ProfileModal.tsx
- src/components/meetingPostDetailView/CommentsList.tsx
- src/pages/MeetingPostDetailView.tsx
- src/store/login.ts
- src/types/userInfoType.ts
- 프로필 내 좋아요 기능
- 프로필 모달에서 좋아요 누르면 +1
- 이미 좋아요 선택된 하트를 누르면 좋아요 -1
#113
> FOODMATE #113 좋아요 기능 추가

- src/components/common/PostCard.tsx
- src/components/meetingInfo/MeetingInfoCard.tsx
- src/components/meetingInfo/MeetingInfoCardList.tsx
- src/components/meetingInfo/MeetingInfoRequestCard.tsx
- src/pages/FindFoodmate.tsx
- src/pages/History.tsx
- src/pages/Inquiry.tsx
- src/pages/MeetingPostDetailView.tsx
- src/pages/Neighborhood.tsx
- src/store/meetingInfo.ts
- src/types/postCardType.ts
- src/utils/formatDate.ts
- DB 데이터 연동
- 세부 카테고리 삭제
- 데이터 받아와서 뿌리기
- 카드 클릭 시 모임 상세 페이지로 이동
- #115
> FOODMATE #115 신청 내역 페이지 데이터 연동

- src/pages/MeetingPostDetailView.tsx
- 모임 참여 기능 추가 
- 내가 작성한 모임글에는 모임 참여/대화 참여 버튼 숨기기
- 이미 신청한 모임에는 "해당 모임에 신청 이력이 존재합니다." 경고창
- 모임 참여 기능
- #120
> FOODMATE #120 모임 참여 기능 추가 

- src/api/ChatApi.ts
- src/api/memberApi.ts
- src/components/chat/Home.tsx
- src/components/chat/MemberThumbnail.tsx
- src/components/chat/Message.tsx
- src/components/common/Nav.tsx
- src/constants/auth.ts
- src/hooks/useChatroomMessage.ts
- src/hooks/useMyProfile.ts
- src/pages/Chat.tsx
- src/pages/MeetingPostDetailView.tsx
- Nav API 연동
- 채팅 페이지 버그 수정
- Nav API 연동(로그인 전/후, 로그아웃)
- 채팅 페이지 버그 수정
- 채팅 페이지 스타일 수정
- 로그인 후 Nav
- 로그인 전, Nav 
-  ISSUE #85
> FOODMATE #85 Nav API 연동

- src/api/memberApi.ts
- src/constants/mypage.ts
- src/pages/Register.tsx
- src/types/registerType.ts
- 회원 가입 페이지 리팩토링
- UI는 그대로 진행
- 일반 회원 가입만 구현
- 메뉴 선택시 "·" 제거 후 데이터 전송
- #122
> FOODMATE #122 회원 가입 페이지 리팩토링

- src/components/common/Nav.tsx
- src/pages/MeetingPostDetailView.tsx
- 채팅 참여 기능 개발
- 채팅 참여 기능 재추가
- Nav 컴포넌트 스타일 수정
- ISSUE #126
> FOODMATE #126 채팅 참여 기능 재추가
